# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6380eba84dc8a97d212876b3b49271da0bb4714f09482ab2384e7829b86b50c35b5657d3180da92f7106b6db9bc7e562e0675911e1e8390e865e60c5f82d5bf

test:
  secret_key_base: 3786edf03c068cecdb1c5cf66c2cfad7aa1f842afa09b0aa1c2b676dc7bfc89cb55f9cec25902ac1e608c3f3fa8b7b2032f0d259fc47f8eddd80c43d3391fd64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
